# Generated by Django 5.0.1 on 2024-02-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_correta', models.CharField(max_length=100)),
                ('resposta', models.CharField(max_length=100)),
                ('foto_card', models.CharField(max_length=100)),
            ],
        ),
    ]
