# Generated by Django 5.0.1 on 2024-02-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_rename_resposta_card_alternativa_dois_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='alternativa_cinco',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
