# Generated by Django 5.0.1 on 2024-02-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_card_resposta_correta'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='nome_card',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='resposta_correta',
            field=models.CharField(default='', max_length=100),
        ),
    ]
