# Generated by Django 5.0.1 on 2024-02-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_card_nome_card_alter_card_resposta_correta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='nome_card',
            new_name='nome_do_card',
        ),
    ]
