# Generated by Django 5.0.1 on 2024-02-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_rename_nome_card_card_nome_do_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='classe_do_card',
            field=models.CharField(choices=[('', 'Selecione a classe do card'), ('Frutas', 'Frutas'), ('Animais', 'Animais'), ('Objetos', 'Objetos'), ('Pessoas', 'Pessoas'), ('Veículos', 'Veículos')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='foto_card',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='resposta_correta',
            field=models.CharField(max_length=100),
        ),
    ]
