# Generated by Django 5.0.1 on 2024-02-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_card_classe_do_card_alter_card_foto_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
