# Generated by Django 5.0.1 on 2024-02-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_card_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='foto_card',
            field=models.ImageField(blank=True, null=True, upload_to='cards_fotos/%Y/%m/%d/'),
        ),
    ]
