# Generated by Django 5.0.1 on 2024-02-09 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_alter_card_foto_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertou', models.BooleanField()),
                ('data_acerto', models.DateTimeField(auto_now_add=True)),
                ('data_erro', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
            ],
            options={
                'verbose_name': 'Aluno_Card',
                'verbose_name_plural': 'Alunos_Cards',
                'unique_together': {('aluno', 'card')},
            },
        ),
        migrations.AddField(
            model_name='card',
            name='aluno',
            field=models.ManyToManyField(through='cards.Aluno_Card', to=settings.AUTH_USER_MODEL),
        ),
    ]
